name = "pindarosql"
compatibility_date = "2023-01-01"
# development environment
main = "src/index.ts"
# development environment
[vars]
ENV = "development"
DB_HOST = ""
DB_USERNAME = ""
DB_PASSWORD = ""


# production environment
[env.production]
name = "pindarosqlprod"
[env.production.vars]
ENV = "production"
DB_HOST = ""
DB_USERNAME = ""
DB_PASSWORD = ""